
    <div class="photo-gallery">
        <div class="container" style="background-color:#61122f;">
            <div class="intro">
                <h2 class="text-nowrap text-center" style="color:#d6d6d8;">Menu Category</h2>
            </div>

           <?php if(isset($view)){?>
            
           <div class="row photos">
           <?php foreach($values as $user): ?>
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="assets/img/<?php echo $user->Image?>" data-lightbox="photos"><img class="img-thumbnail img-fluid" src="assets/img/menun.jpg" data-bs-hover-animate="bounce" style="width:330px;height:200px;margin-top:15px;"></a>
                    <p class="text-center" style="color:#ffffff;margin-bottom:0px;"><?php echo $user->Price;?>&nbsp;<button class="btn btn-dark btn-sm" type="button">Order</button></p>
                    <p class="text-center" style="color:#ffffff;"><?php echo $user->Title?></p>
                </div>
                
                <?php  endforeach; ?>
                <?php  }else{ ?>
            <section class="d-inline-flex row" style="padding:12px;width:100%;">      
            <?php foreach($values as $user):?>
            <div class="menu-tile col-md-6">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="menu-photo">  
                            <div class="id" style="height:28px;width:42px;margin-bottom:5px;margin-right:5px;">
                                <p  style="width:48px;color:#ffffff;"><?php echo $user->Menu_id;?></p>
                            </div><img  class="img-thumbnail" src="assets/img/<?php echo $user->Image?>"> </div>
                        <div class="d-flex justify-content-center align-items-center align-content-sm-center align-content-md-center align-content-lg-center align-content-xl-center menu-price"
                            style="color:#ffffff;margin-left:5px;">
                            <p  class="text-center d-flex" style="width:146px;"> <?php echo $user->Price;?>&nbsp;&nbsp<button class="btn btn-dark btn-sm" name = "add" type="button">Order</button></p>
                        </div>
                    </div> 
                    <div class="menu-description col-sm-7">
                        <h3  style="color:rgb(255,255,255);"><?php echo $user->Title;?></h3>
                        <p  class="menu-detail" style="color:#ffffff;"><em><?php echo $user->Description;?></em></p>
                        <p style="color:#ffffff;"><?php echo $user->Status;?></p>
                    </div>
                </div>
            </div> <?php endforeach;?>
            
          <?php } ?>
                </section>


