

<section class="container">
    <form action = '' method = 'POST'>
        <fieldset style="background-color:#61122f;color:#ffffff;">
            <legend style="margin-bottom:26px;">Delivery Details</legend>
            <div class="order-labell">
                <p>Full Names</p><?php echo isset($error['fullName'])?$error['fullName'] :''?><input type="text" class="input-response" name="fullName"></div>
            <div class="order-labell">
                <p>Phone Number</p><?php echo isset($error['phoneNo'])?$error['phoneNo'] :''?><input type="tel" class="input-response" name="phoneNo"></div>
            <div class="order-labell">
                <p>Email</p><?php echo isset($error['email'])?$error['email'] :''?><input type="email" class="input-response" name="email"></div>
            <div class="order-labell">
                <p>Address</p><?php echo isset($error['address'])?$error['address'] :''?><textarea class="input-response" name="address"></textarea></div>
            <div class="order-labell">
                <p>Total:<?=Cart::getPrice() ?></p>
            </div>
            <div class="order-labell">
                <p>Cash on delivery</p>
                <div class="form-check"><?php echo isset($error['checkbox'])?$error['checkbox'] :''?><input class="form-check-input" checked type="radio" id="formCheck-1" name="checkbox"><label class="form-check-label" for="formCheck-1">Checked</label></div>
                
                <button class="btn btn-primary float-left" type="submit" name="submit" style="width:124px;">Purchase</button></div>
                
        </fieldset>
    </form>
</section>