
    <div>
        <div class="jumbotron jumbotron-fluid" style="height:295px;background-repeat:no-repeat;background-size:cover;background-color:#35525B;margin-bottom:0px;">
            <h1 class="text-center">Contact us</h1>
            <p class="text-center" style="color:#ffffff;font-size:17px;"><br>Send us a message and we’ll get back to you as soon as possible.<br>You can also reach us by phone at&nbsp;<a href="tel:3476894287">015–249–8451</a>&nbsp;or email&nbsp;<a href="mailto:info@coloniaverdenyc.com">info@grapevine.com</a>. Looking
                forward to hearing from you.<br><br><br></p>
            <p></p>
        </div>
    </div>
    <div class="intro"></div>
    <div data-aos="zoom-out" class="register-photo" style="background-color:#B3DEE5;">
        <div class="form-container">
            <form method="post">
                <div class="form-group"><?= isset($error['firstname'])?$error['firstName'] :''?><input class="form-control" type="text" name="firstName" value="firstName" autofocus=""></div>
                <div class="form-group"><?= isset($error['lastName'])?$error['lastName'] :''?><input class="form-control" type="text" name="lastName" value="lastName" ></div>
                <div class="form-group"><?= isset($error['email'])?$error['email'] :''?><input class="form-control" type="email" name="email"  placeholder="email"></div>
                <div class="form-group"><?= isset($error['phone'])?$error['phone'] :''?><input class="form-control" type="tel" name="phone" placeholder="phone no"></div>
                <div class="form-group"><?= isset($error['category'])?$error['category'] :''?><select class="form-control" name ="category"><option value="12">Category</option><option value="13">Press</option><option value="14">Catering</option></select></div>
                <div class="form-group"><?= isset($error['comment'])?$error['comment'] :''?><textarea class="form-control" name ="comment" wrap="hard" style="height:148px;">Message</textarea></div>
                <div class="form-group"><button class="btn btn-warning btn-block btn-lg" name ='submit'  type="submit" style="width:237px;">Submit</button></div>
            </form>
        </div>
    </div>
