<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project1 backup3</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aguafina+Script">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxygen+Mono">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.css">
</head>

<body style="background-color:#ffffff;">
    <nav class="navbar navbar-light navbar-expand-md" style="background-color:#ffcc1e;margin-bottom:0px;">
        <div class="container-fluid"><a class="navbar-brand" href="homepage.html" style="color:#000000;font-style:italic;font-weight:bold;font-size:21px;">K&amp;C Restaurant</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div
                class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="homepage.html" style="color:#000000;font-size:21px;">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="Category.html" style="color:#000000;font-size:21px;">Category</a></li>
                    <li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#" style="color:#000000;font-size:21px;">Specials</a>
                        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="specials-1.html">Beef Steak</a><a class="dropdown-item" role="presentation" href="specials-2.html">Beef Stew</a><a class="dropdown-item" role="presentation" href="specials-3.html">Veggies</a></div>
                    </li>
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="Sign up.html" style="color:#000000;font-size:21px;">Sign up</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="Contact us.html" style="color:#000000;font-size:21px;">Contact us</a></li>
                </ul>
        </div>
        </div>
    </nav>
    <div>
        <div class="jumbotron jumbotron-fluid" style="height:295px;background-repeat:no-repeat;background-size:cover;background-color:#35525B;margin-bottom:0px;">
            <h1 class="text-center">Contact us</h1>
            <p class="text-center" style="color:#ffffff;font-size:17px;"><br>Send us a message and we’ll get back to you as soon as possible.<br>You can also reach us by phone at&nbsp;<a href="tel:3476894287">015–249–8451</a>&nbsp;or email&nbsp;<a href="mailto:info@coloniaverdenyc.com">info@grapevine.com</a>. Looking
                forward to hearing from you.<br><br><br></p>
            <p></p>
        </div>
    </div>
    <div class="intro"></div>
    <div data-aos="zoom-out" class="register-photo" style="background-color:#B3DEE5;">
        <div class="form-container">
            <form method="post">
                <div class="form-group"><input class="form-control" type="text" name="Name" value="Name" required="" autofocus=""></div>
                <div class="form-group"><input class="form-control" type="text" name="Last Name" value="Last Name" required=""></div>
                <div class="form-group"><input class="form-control" type="email" name="email" required="" placeholder="Email"></div>
                <div class="form-group"><input class="form-control" type="password" name="password" required="" placeholder="Password"></div>
                <div class="form-group"><select class="form-control" required=""><option value="" selected="">Select category</option><option value="12">Category</option><option value="13">Press</option><option value="14">Catering</option></select></div>
                <div class="form-group"><textarea class="form-control" wrap="hard" required="" style="height:148px;">Message</textarea></div>
                <div class="form-group"><button class="btn btn-warning btn-block btn-lg" type="submit" style="width:237px;">Submit</button></div>
            </form>
        </div>
    </div>
    <div class="footer-dark" style="background-color:#505e6c;">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Address</h3>
                        <ul>
                            <li><a href="#">66 Market street</a></li>
                            <li><a href="#">Polokwane &nbsp;0700</a></li>
                            <li><a href="#">Tel no &nbsp; 015 249 8451</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Working hours</h3>
                        <ul>
                            <li>Mon Fri &nbsp;09h00 - &nbsp;20h30</li>
                            <li><a href="https://bootstrapstudio.io/releases/app/4.1.7/#">Sat &nbsp; &nbsp;09h00- 21h00</a><br></li>
                            <li><a href="#">Sun &nbsp; Closed</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Our mission</h3>
                        <p>Our mission is to ensure that we provide the greatest taste in the world.The food is made to perfection,our chef use &nbsp;fresh ingrideints carefully sourced to create unforgetable memories<br><br></p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">K&amp;C Restaurant © 2021</p>
            </div>
        </footer>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    <script src="assets/js/script.min.js"></script>
</body>

</html>