
<section>
        <div class="container">
            <h1 class="text-center" style="color:#f9ddd6;">CartItems</h1>
            <div class="table-responsive" style="padding:20px;padding-right:20px;">
            <form action ='food' method ='POST'>
                <table class="table">
                    <thead style="padding:21px;padding-top:0px;padding-right:25px;padding-bottom:0px;padding-left:0px;">
                        <tr>
                            <th style="color:#f9ddd6;">Title</th>
                            <th style="color:#f9ddd6;">Price</th>
                            <th style="color:#f9ddd6;">Quantity</th>
                            <th style="color:#f9ddd6;">SubTotal</th>
                        </tr>
                    </thead>
                    <?php 
                    //retrieve items within nested loop
                            foreach($products as $item):
                                foreach($item as $item):?>
                    <tbody>
                        <tr>
                            <td style="color:#f9ddd6;"><?= $item->title;?></td>
                            <td style="color:#f9ddd6;"><?= $item->price;?></td>
                            
                            <td style="color:#f9ddd6;" >
                          
                            <input type ="number" name="qnt<?= $item->id ?>" id="<?= $item->id ?>"   size = "3" min="1" max="10" value="<?=Cart::qnt($item->id) ?>"/>
                            <button name="update" id="<?= $item->id ?>" value="<?= $item->id ?>"> update </button>
                            <button type="delete" name="delete" id="<?= $item->id ?>" value="<?= $item->id ?>"> delete </button>
                        </td>
                        <td style="color:#f9ddd6;"><?= $item->price * Cart::qnt($item->id)?></td>
                        </tr>
                        
                        <?php 
                                endforeach;
                            endforeach;?>
                        <th>
                        <td style="color:#f9ddd6;">Total:<?= Cart::getPrice() ?></td><br/><br/><td></td>
                        <td style="color:#f9ddd6;"><a href="checkOut"><input type="submit" name="checkout" value="Confirm Order" class="btn btn-success"/></a></td>
                        </th>
                    
                    </tbody>
                   
                    </table>
               </form>
            </div>
        </div>
    </section>

  