
	<div class="jumbotron" style="height:369px;background-color:#61122f;background-image:url(&quot;assets/img/jumbotron_1200.jpg&quot;);margin-bottom:0px;margin-left:12px;margin-right:12px;margin-top:12px;"></div>
    <div class="article-list" style="background-color:#61122f;">
        <div class="container">
            <div class="intro"></div>
            <div class="row articles">
                <div class="col-sm-6 col-md-4 item" style="height:378px;"><a href="<?php echo User::getImage('category');?>"><img class="img-thumbnail img-fluid" src="assets/img/menu-tile1.jpg" data-bs-hover-animate="jello" style="height:210px;"><span class="d-flex justify-content-center">Menu</span></a></div>
                <div class="col-sm-6 col-md-4 item"
                    style="height:378px;"><a href="<?php echo User::getImage('Special');?>"><img class="img-thumbnail img-fluid" src="assets/img/specials-tile1.jpg" data-bs-hover-animate="jello" style="height:208px;"><span class="d-flex justify-content-center">Specials</span></a></div>
                <div class="col-sm-6 col-md-4 item col-sm-12"
                    style="height:378px;"><a href="<?php echo User::getImage('Destination');?>"><img class="img-thumbnail img-fluid" src="assets/img/map.jpg" data-bs-hover-animate="jello" style="height:210px;"><span class="d-flex justify-content-center" style="color:rgb(0,123,255);">Destination</span></a></div>
            </div>
        </div>
    </div>
