<section class="d-inline-flex row" style="padding:12px;width:100%;">
<?php
    foreach($values as $ent):
        if($ent[0]->type == Types::BEEF): 
            echo '<br/><h1 class="text-center" style="color:#f9ddd6;">Beef</h1><br/>' ;
        elseif($ent[0]->type == Types::STEW):
            echo '<br/><h1 class="text-center" style="color:#f9ddd6;">Beef Stew</h1><br/>';
        elseif($ent[0]->type == Types::VEGGIES):
            echo '<br/><h1 class="text-center" style="color:#f9ddd6;">Veggies</h1><br/>';
        elseif($ent[0]->type == Types::CHICKEN):
            echo '<br/><h1 class="text-center" style="color:#f9ddd6;">Chicken</h1><br/> ';
        endif;
        
        foreach($ent as $product):
?>    
            <div class="menu-tile col-md-6">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="menu-photo">  
                            <div class="id" style="height:28px;width:42px;margin-bottom:5px;margin-right:5px;">
                                <p  style="width:48px;color:#ffffff;"><?= $product->menu_id;?></p>
                            </div><img  class="img-thumbnail" src="assets/img/<?= $product->image?>"> </div>
                        <div class="d-flex justify-content-center align-items-center align-content-sm-center
                        align-content-md-center align-content-lg-center align-content-xl-center menu-price"
                            style="color:#ffffff;margin-left:5px;">
                            <p  class="text-center d-flex" style="width:146px;"> <?= $product->price;?>&nbsp;&nbsp
                            <?php 
                                if($product->status == 1):
                                    echo Cart::btn($product->id);   
                                endif 
                            ?></p>
                        </div>
                    </div> 
                    <div class="menu-description col-sm-7">
                        <h3  style="color:rgb(255,255,255);"><?= $product->title;?></h3>
                        <p  class="menu-detail" style="color:#ffffff;"><em><?= $product->description;?></em><br></p>
                        <p style="color:#ffffff;"><?= ($product->status == 1)?'Instock' :'Unavailable'; ?></p>
                    </div>
                </div>
            </div> 
<?php
        endforeach;
    endforeach;
?>
</section>



 
