
    <div class="article-list"></div>
    <div class="register-photo" style="background-color:#61122f;">
        <h2 class="text-center text-white" style="margin-bottom:26px;color:#ffffff;">Subscribe for our news letter and products</h2>
        <div class="form-container" style="height:490px;">
            <div class="image-holder" style="background-image:url(&quot;assets/img/register_early.jpg&quot;);"></div>
            <form method="post">
                <h2 class="text-center"><strong>Sign up</strong></h2>
                <div class="form-group"><?= isset($error['firstName'])?$error['firstName'] :''?><input class="form-control" type="text" name="firstName" placeholder="firstName"></div>
                <div class="form-group"><?= isset($error['lastName'])?$error['lastName'] :''?><input class="form-control" type="text" name="lastName" placeholder="lastName"></div>
                <div class="form-group"><?= isset($error['email'])?$error['email'] :''?><input class="form-control" type="email" name="email" placeholder="email"></div>
                <div class="form-group"><button class="btn btn-primary active btn-block" name="subscribe" value = "submit" type="submit" style="background-color:#1485ee;">Subscribe</button></div>
                <a class="text-monospace already" href="#" style="font-size:14px;color:#282d32;">&nbsp;We voucher your privacy, no spam!&nbsp;</a></form>
        </div>
    </div>
