<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project1 backup3</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aguafina+Script">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxygen+Mono">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.css">
</head>

<body style="background-color:rgb(255,255,255);">
    <nav class="navbar navbar-light navbar-expand-md" style="margin-bottom:0px;background-color:#ffcc1e;">
        <div class="container"><a class="navbar-brand" href="homepage.html" style="font-style:italic;font-weight:bold;">K&amp;C Restaurant</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div
                class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="homepage.html" style="font-size:21px;">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="Category.html" style="font-size:21px;">Category</a></li>
                    <li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#" style="color:#000000;font-size:21px;">Specials</a>
                        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="specials-1.html">Beef Steak</a><a class="dropdown-item" role="presentation" href="specials-2.html">Beef Stew</a><a class="dropdown-item" role="presentation" href="specials-3.html">Veggies</a></div>
                    </li>
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="Sign up.html" style="font-size:21px;">Sign up</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="Contact us.html" style="font-size:21px;">Contact us</a></li>
                </ul>
        </div>
        </div>
    </nav>
    <div class="article-list"></div>
    <div class="register-photo" style="background-color:#61122f;">
        <h2 class="text-center text-white" style="margin-bottom:26px;color:#ffffff;">Subscribe for our news letter and products</h2>
        <div class="form-container" style="height:490px;">
            <div class="image-holder" style="background-image:url(&quot;assets/img/register_early.jpg&quot;);"></div>
            <form method="post">
                <h2 class="text-center"><strong>Sign up</strong></h2>
                <div class="form-group"><input class="form-control" type="text" name="First Name" placeholder="First Name"></div>
                <div class="form-group"><input class="form-control" type="text" name="Last Name" placeholder="Last Name"></div>
                <div class="form-group"><input class="form-control" type="email" name="Email" placeholder="Email"></div>
                <div class="form-group"><button class="btn btn-primary active btn-block" type="submit" style="background-color:#1485ee;">Subscribe</button></div><a class="text-monospace already" href="#" style="font-size:14px;color:#282d32;">&nbsp;We voucher your privacy, no spam!&nbsp;</a></form>
        </div>
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Address</h3>
                        <ul>
                            <li><a href="#">66 Market street</a></li>
                            <li><a href="#">Polokwane &nbsp;0700</a></li>
                            <li><a href="#">Tel no &nbsp;015 294 8451</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Working Hours</h3>
                        <ul>
                            <li><a href="#">Mon &nbsp;Fri 09h00-20h30<br></a></li>
                            <li><a href="#">Sat &nbsp; 09h00- 21h00</a></li>
                            <li><a href="#">Sun &nbsp; Closed</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Our mission</h3>
                        <p>Our mission is to ensure that we provide the greatest taste in the world.The food is made to perfection,our chef use &nbsp;fresh ingrideints carefully sourced to create unforgetable memories<br><br></p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">K&amp;C Restaurant © 2021</p>
            </div>
        </footer>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    <script src="assets/js/script.min.js"></script>
</body>

</html>