 <?php 
$user = new product(); 
$values = '';
?>
    <?php foreach($values as $user):?>
    <section class="d-inline-flex row" style="padding:12px;width:100%;">
        <div class="menu-tile col-md-6">
            <div class="row">
                <div class="col-sm-5">   
                    <div class="menu-photo">  
                    div class="id" style="height:28px;width:42px;margin-bottom:5px;margin-right:5px;">
                            <p style="width:48px;color:#ffffff;"><?php echo $user->getname();?></p>
                        <div><img  class="img-thumbnail" src="assets/img/C2-2.jpg"><?php echo $values->getImage();?></div>
                    <div class="d-flex justify-content-center align-items-center align-content-sm-center align-content-md-center align-content-lg-center align-content-xl-center menu-price"
                        style="color:#ffffff;margin-left:5px;">
                        <p  class="text-center d-flex" style="width:146px;"> <?php echo $user->getPrice();?></p>
                    </div> 
                </div> 
                <div class="menu-description col-sm-7">
                    <h3  style="color:rgb(255,255,255);"><?php echo $user->getTitle();?></h3>
                    <p  class="menu-detail" style="color:#ffffff;"><em><?php echo $product->getDesription();?></em><br><br><br></p>
                    <?php endforeach; ?></div>
            </div>
        </div> 
       
    <section>