<section class="d-inline-flex row" style="padding:12px;width:100%;">
<?php

if( ! isset($view)):
?><?php foreach($values as $product): ?>
 <div class="menu-tile col-md-6">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="menu-photo">  
                            <div class="id" style="height:28px;width:42px;margin-bottom:5px;margin-right:5px;">
                                <p  style="width:100px;color:#ffffff;">
                                <a href="special&sp=<?= $product->type?>">
                                <?php 
                                    if($product->type == Types::BEEF): 
                                        echo "Beef" ;
                                    elseif($product->type == Types::STEW):
                                        echo "Stew";
                                    elseif($product->type == Types::VEGGIES):
                                        echo "Veggies";
                                    elseif($product->type == Types::CHICKEN):
                                        echo "Chicken";
                                    endif;
                                ?>      </em></a>
                                </p>
                            </div>
                                <img  class="img-thumbnail" src="assets/img/<?= $product->image?>">
                
                            </div>
                            
                    </div> 
                    <div class="menu-description col-sm-7"> 
                    </div>
                </div>
            </div> 
     <?php  endforeach; ?>
<?php  
 else:  
    foreach($values as $product):

        if( $product->status == 1 && $product->special == 1 ):
?>
            <div class="menu-tile col-md-6">
                <div class="row">
                    <div class="col-sm-5">
                        <div class="menu-photo">  
                            <div class="id" style="height:28px;width:42px;margin-bottom:5px;margin-right:5px;">
                                <p  style="width:48px;color:#ffffff;"><?= $product->menu_id;?></p>
                            </div><img  class="img-thumbnail" src="assets/img/<?= $product->image?>"> </div>
                        <div class="d-flex justify-content-center align-items-center align-content-sm-center align-content-md-center align-content-lg-center align-content-xl-center menu-price"
                            style="color:#ffffff;margin-left:5px;">
                            <p  class="text-center d-flex" style="width:146px;"> <?= $product->price;?>&nbsp;&nbsp<?= Cart::btn($product->id) ?></p>
                        </div>
                    </div> 
                    <div class="menu-description col-sm-7">
                        <h3  style="color:rgb(255,255,255);"><?= $product->title;?></h3>
                        <p  class="menu-detail" style="color:#ffffff;"><em><?= $product->description;?></em></p>
                    </div>
                </div>
            </div> 
<?php 
        endif;
    endforeach;
endif;
?>
</section>